#!/bin/bash
# init script to start ofagent
### BEGIN INIT INFO
# Provides:          ON.Lab
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OF-DPA ofagent
# Description:       OF-DPA ofagent.
### END INIT INFO

PID_FILE="/var/run/ofagent"
CONFIG_FILE="/etc/ofagentapp/config"
LOG_PATH="/var/log/ofagentapp"

if [ ! -d $LOG_PATH ]; then
    mkdir -p $LOG_PATH
fi

for fn in `command ls $LOG_PATH | grep "log" | sort -r`; do
    num=`echo "$fn" | grep -e "\d\{1,\}$" -o`
    new_num=$((num+1))
    if [ -f "$LOG_PATH/log.$num" ]; then
        mv "$LOG_PATH/log.$num" "$LOG_PATH/log.$new_num"
    fi
done

if [ -f $LOG_PATH/log ]; then
    mv $LOG_PATH/log $LOG_PATH/log.1
fi

for fn in `command ls $LOG_PATH | grep error | sort -r`; do
    num=`echo "$fn" | grep -e "\d\{1,\}$" -o`
    new_num=$((num+1))
    if [ -f "$LOG_PATH/error.$num" ]; then
        mv "$LOG_PATH/error.$num" "$LOG_PATH/error.$new_num"
    fi
done

if [ -f $LOG_PATH/error ]; then
    mv $LOG_PATH/error $LOG_PATH/error.1
fi

LOG_FILE=$LOG_PATH/log
ERROR_LOG_FILE=$LOG_PATH/error

touch $LOG_FILE
touch $ERROR_LOG_FILE

if [ -f $CONFIG_FILE ]; then
    echo "Using config file $CONFIG_FILE" >> $LOG_FILE
    source $CONFIG_FILE
fi

[ ! -z $CTRL_IP ] || CTRL_IP="127.0.0.1"
[ ! -z $CTRL_PORT ] || CTRL_PORT="6653"
[ ! -z $DPID ] || DPID="1"

case "$1" in
start)
    launcher ofagentapp -t $CTRL_IP:$CTRL_PORT -i $DPID $OPT_ARGS > $LOG_FILE 2> $ERROR_LOG_FILE &
    ;;
stop)
    kill -9 `echo $PID_FILE`
    ;;
*)
    echo "Usage /etc/init.d/ofagentd {start|stop}"
    ;;
esac
