#!/bin/bash
# init script to start ofagent
### BEGIN INIT INFO
# Provides:          ofagent
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OF-DPA ofagent
# Description:       OF-DPA ofagent.
### END INIT INFO

PID_FILE="/var/run/ofagent/.pid"
CONFIG_FILE="/etc/ofagentapp/config"
LOG_PATH="/var/log/ofagentapp"
LAUNCH_CMD="/usr/sbin/launcher ofagentapp"
LOG_FILE=$LOG_PATH/log
ERROR_LOG_FILE=$LOG_PATH/error
BASH="/bin/bash"

if [ ! -d $LOG_PATH ]; then
    mkdir -p $LOG_PATH
fi

shift_logs () {
    for fn in `command ls $LOG_PATH | grep "log" | sort -r`; do
        num=`echo "$fn" | grep -e "[0-9]\{1,\}$" -o`
        if [ ! -z $num ]; then
            new_num=$((num+1))
            if [ -f "$LOG_PATH/log.$num" ]; then
                mv "$LOG_PATH/log.$num" "$LOG_PATH/log.$new_num"
            fi
        fi
    done
    
    if [ -f $LOG_PATH/log ]; then
        mv $LOG_PATH/log $LOG_PATH/log.1
    fi
    
    for fn in `command ls $LOG_PATH | grep error | sort -r`; do
        num=`echo "$fn" | grep -e "[0-9]\{1,\}$" -o`
        new_num=$((num+1))
        if [ -f "$LOG_PATH/error.$num" ]; then
            mv "$LOG_PATH/error.$num" "$LOG_PATH/error.$new_num"
        fi
    done
    
    if [ -f $LOG_PATH/error ]; then
        mv $LOG_PATH/error $LOG_PATH/error.1
    fi

}

create_log_files () {
    touch $LOG_FILE
    touch $ERROR_LOG_FILE
}



start () {
    shift_logs
    create_log_files
    if [ -f $CONFIG_FILE ]; then
        echo "Using config file $CONFIG_FILE" >> $LOG_FILE
        . $CONFIG_FILE
    fi
    
    [ ! -z $CTRL_IP ] || CTRL_IP="127.0.0.1"
    [ ! -z $CTRL_PORT ] || CTRL_PORT="6653"
    [ ! -z $DPID ] || DPID="1"

    AGENT_ARGS="-t $CTRL_IP:$CTRL_PORT -i $DPID $OPT_ARGS"

    [ -f $PID_FILE ] && PID=`cat $PID_FILE` && ps -eo pid | grep -q $PID && \
        echo "Ofagent is already running" && exit 0
    echo -n "Starting ofagent"

    # Currently we don't use start-stop-daemon because we can't get output(logs)
    # from agent.
    #start-stop-daemon --signal INT --start --background --exec $LAUNCH_CMD --\
    #    "-t $CTRL_IP:$CTRL_PORT -i $DPID $OPT_ARGS" > $LOG_FILE 2> $ERROR_LOG_FILE

    $LAUNCH_CMD $AGENT_ARGS > $LOG_FILE 2> $ERROR_LOG_FILE &
    echo "."
}

stop () {
    echo -n "Stopping ofagent"
    [ -f $PID_FILE ] && PID=`cat $PID_FILE` && ps -eo pid | grep -q $PID \
        && kill -9 `cat $PID_FILE`
    echo "."
}

status () {
    [ ! -f $PID_FILE ] && echo "Ofagent is not running" && exit 0
    PID=`cat $PID_FILE`
    ps -eo pid | grep -q $PID && echo "Ofagent is running" || \
        echo "Ofagent is not running"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "Usage /etc/init.d/ofagentd {start|stop|status}"
    ;;
esac
